[package]
name = "dido"
description = "Data In, Data Out"
authors = ["Folyd"]
homepage = "https://github.com/datagogo/dido"
repository = "https://github.com/datagogo/dido"
version = "0.0.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
